services:
  db:
    container_name: res-appStore
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: appStore
    ports:
      - 3307:3306

  adminer:
    container_name: appStore_adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '8082:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '8025:25'